# Generated by Django 4.2.21 on 2025-11-24 11:25

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('original_storage', models.BigIntegerField(default=0)),
                ('total_storage', models.BigIntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Storage Statistics',
                'db_table': 'storage_stats',
            },
        ),
        migrations.CreateModel(
            name='RateLimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rate_limit_tracker',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='rate_limit__user_id_cd3eac_idx')],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('is_reference', models.BooleanField(default=False)),
                ('reference_count', models.IntegerField(default=0)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='files.file')),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user_id', 'uploaded_at'], name='uploaded_fi_user_id_3f857a_idx'), models.Index(fields=['file_hash', 'user_id'], name='uploaded_fi_file_ha_5f1987_idx'), models.Index(fields=['file_type'], name='uploaded_fi_file_ty_206d78_idx')],
            },
        ),
    ]
