# Generated by Django 4.2.21 on 2025-11-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagestats',
            old_name='original_storage',
            new_name='original_storage_used',
        ),
        migrations.RenameField(
            model_name='storagestats',
            old_name='total_storage',
            new_name='total_storage_used',
        ),
    ]
